name = "PiADS1x15"
uuid = "d8234959-29e2-4ab0-a1ab-dffd73ee73d2"
authors = ["Martin Kosch"]
version = "0.1.0"

[deps]
PiGPIO = "bb151fc1-c6dc-5496-8ed6-07f94907e623"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
